logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: DEBUG
        type:
          descriptor:
            sql: trace
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M
      - %msg%n'
spring:      
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: marcio
    password: marcio
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      ddl-auto: none # Use 'update' for development, 'none' for production
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      generate-ddl: false    
  liquibase:
    enabled: false
  profiles:
    active: '@spring.profiles.active@'     

api:
  security:
    secret: ${JWT_SECRET:my-secret-key}
